/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Synapse.API | openapi
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateWorkOrderRequest,
  GetApiWorkOrdersParams,
  UpdateWorkOrderRequest
} from '../../src/generated/model';

import { apiClient } from '../../src/services/apiClient';




/**
 * @summary 製造指示一覧を取得する。
ステータス・日付範囲でフィルタリング可能（製造指示一覧画面 SCR-MO-001 対応）。
 */
export const getApiWorkOrders = (
    params?: GetApiWorkOrdersParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/work-orders`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiWorkOrdersQueryKey = (params?: GetApiWorkOrdersParams,) => {
    return [
    `/api/work-orders`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiWorkOrdersQueryOptions = <TData = Awaited<ReturnType<typeof getApiWorkOrders>>, TError = unknown>(params?: GetApiWorkOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkOrders>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkOrdersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkOrders>>> = ({ signal }) => getApiWorkOrders(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiWorkOrders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkOrders>>>
export type GetApiWorkOrdersQueryError = unknown


export function useGetApiWorkOrders<TData = Awaited<ReturnType<typeof getApiWorkOrders>>, TError = unknown>(
 params: undefined |  GetApiWorkOrdersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkOrders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkOrders>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkOrders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkOrders<TData = Awaited<ReturnType<typeof getApiWorkOrders>>, TError = unknown>(
 params?: GetApiWorkOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkOrders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkOrders>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkOrders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkOrders<TData = Awaited<ReturnType<typeof getApiWorkOrders>>, TError = unknown>(
 params?: GetApiWorkOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkOrders>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 製造指示一覧を取得する。
ステータス・日付範囲でフィルタリング可能（製造指示一覧画面 SCR-MO-001 対応）。
 */

export function useGetApiWorkOrders<TData = Awaited<ReturnType<typeof getApiWorkOrders>>, TError = unknown>(
 params?: GetApiWorkOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkOrders>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkOrdersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary 製造指示を発行する（MO-001）。
製造指示番号は MO-YYYYMMDD-NNNN 形式で自動採番される。
発行者は JWT クレームから自動取得する。
 */
export const postApiWorkOrders = (
    createWorkOrderRequest: CreateWorkOrderRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/work-orders`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createWorkOrderRequest, signal
    },
      );
    }
  


export const getPostApiWorkOrdersMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWorkOrders>>, TError,{data: CreateWorkOrderRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiWorkOrders>>, TError,{data: CreateWorkOrderRequest}, TContext> => {

const mutationKey = ['postApiWorkOrders'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiWorkOrders>>, {data: CreateWorkOrderRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiWorkOrders(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiWorkOrdersMutationResult = NonNullable<Awaited<ReturnType<typeof postApiWorkOrders>>>
    export type PostApiWorkOrdersMutationBody = CreateWorkOrderRequest
    export type PostApiWorkOrdersMutationError = unknown

    /**
 * @summary 製造指示を発行する（MO-001）。
製造指示番号は MO-YYYYMMDD-NNNN 形式で自動採番される。
発行者は JWT クレームから自動取得する。
 */
export const usePostApiWorkOrders = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWorkOrders>>, TError,{data: CreateWorkOrderRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiWorkOrders>>,
        TError,
        {data: CreateWorkOrderRequest},
        TContext
      > => {

      const mutationOptions = getPostApiWorkOrdersMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 製造指示を1件取得する。
 */
export const getApiWorkOrdersId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/work-orders/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiWorkOrdersIdQueryKey = (id?: string,) => {
    return [
    `/api/work-orders/${id}`
    ] as const;
    }

    
export const getGetApiWorkOrdersIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiWorkOrdersId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkOrdersId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkOrdersIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkOrdersId>>> = ({ signal }) => getApiWorkOrdersId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiWorkOrdersId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkOrdersIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkOrdersId>>>
export type GetApiWorkOrdersIdQueryError = unknown


export function useGetApiWorkOrdersId<TData = Awaited<ReturnType<typeof getApiWorkOrdersId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkOrdersId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkOrdersId>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkOrdersId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkOrdersId<TData = Awaited<ReturnType<typeof getApiWorkOrdersId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkOrdersId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkOrdersId>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkOrdersId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkOrdersId<TData = Awaited<ReturnType<typeof getApiWorkOrdersId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkOrdersId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 製造指示を1件取得する。
 */

export function useGetApiWorkOrdersId<TData = Awaited<ReturnType<typeof getApiWorkOrdersId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkOrdersId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkOrdersIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary 製造指示を更新する（MO-003）。
完了・キャンセル済みは更新不可。着手中は数量変更不可。
 */
export const putApiWorkOrdersId = (
    id: string,
    updateWorkOrderRequest: UpdateWorkOrderRequest,
 ) => {
      
      
      return apiClient<void>(
      {url: `/api/work-orders/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateWorkOrderRequest
    },
      );
    }
  


export const getPutApiWorkOrdersIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiWorkOrdersId>>, TError,{id: string;data: UpdateWorkOrderRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiWorkOrdersId>>, TError,{id: string;data: UpdateWorkOrderRequest}, TContext> => {

const mutationKey = ['putApiWorkOrdersId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiWorkOrdersId>>, {id: string;data: UpdateWorkOrderRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiWorkOrdersId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiWorkOrdersIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiWorkOrdersId>>>
    export type PutApiWorkOrdersIdMutationBody = UpdateWorkOrderRequest
    export type PutApiWorkOrdersIdMutationError = unknown

    /**
 * @summary 製造指示を更新する（MO-003）。
完了・キャンセル済みは更新不可。着手中は数量変更不可。
 */
export const usePutApiWorkOrdersId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiWorkOrdersId>>, TError,{id: string;data: UpdateWorkOrderRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiWorkOrdersId>>,
        TError,
        {id: string;data: UpdateWorkOrderRequest},
        TContext
      > => {

      const mutationOptions = getPutApiWorkOrdersIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 製造指示をキャンセルする（MO-004）。発行済・着手中のみ可能。
 */
export const postApiWorkOrdersIdCancel = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/work-orders/${id}/cancel`, method: 'POST', signal
    },
      );
    }
  


export const getPostApiWorkOrdersIdCancelMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWorkOrdersIdCancel>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiWorkOrdersIdCancel>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiWorkOrdersIdCancel'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiWorkOrdersIdCancel>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiWorkOrdersIdCancel(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiWorkOrdersIdCancelMutationResult = NonNullable<Awaited<ReturnType<typeof postApiWorkOrdersIdCancel>>>
    
    export type PostApiWorkOrdersIdCancelMutationError = unknown

    /**
 * @summary 製造指示をキャンセルする（MO-004）。発行済・着手中のみ可能。
 */
export const usePostApiWorkOrdersIdCancel = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWorkOrdersIdCancel>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiWorkOrdersIdCancel>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiWorkOrdersIdCancelMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 製造指示を着手中に移行する（MO-007）。
発行済（Issued）からのみ遷移可能。着手後は指示数量が変更不可になる。
 */
export const postApiWorkOrdersIdStart = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/work-orders/${id}/start`, method: 'POST', signal
    },
      );
    }
  


export const getPostApiWorkOrdersIdStartMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWorkOrdersIdStart>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiWorkOrdersIdStart>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiWorkOrdersIdStart'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiWorkOrdersIdStart>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiWorkOrdersIdStart(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiWorkOrdersIdStartMutationResult = NonNullable<Awaited<ReturnType<typeof postApiWorkOrdersIdStart>>>
    
    export type PostApiWorkOrdersIdStartMutationError = unknown

    /**
 * @summary 製造指示を着手中に移行する（MO-007）。
発行済（Issued）からのみ遷移可能。着手後は指示数量が変更不可になる。
 */
export const usePostApiWorkOrdersIdStart = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWorkOrdersIdStart>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiWorkOrdersIdStart>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiWorkOrdersIdStartMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 製造指示を完了に移行する（MO-007）。
着手中（InProgress）からのみ遷移可能。完了後は変更・キャンセル不可。
 */
export const postApiWorkOrdersIdComplete = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/work-orders/${id}/complete`, method: 'POST', signal
    },
      );
    }
  


export const getPostApiWorkOrdersIdCompleteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWorkOrdersIdComplete>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiWorkOrdersIdComplete>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiWorkOrdersIdComplete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiWorkOrdersIdComplete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiWorkOrdersIdComplete(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiWorkOrdersIdCompleteMutationResult = NonNullable<Awaited<ReturnType<typeof postApiWorkOrdersIdComplete>>>
    
    export type PostApiWorkOrdersIdCompleteMutationError = unknown

    /**
 * @summary 製造指示を完了に移行する（MO-007）。
着手中（InProgress）からのみ遷移可能。完了後は変更・キャンセル不可。
 */
export const usePostApiWorkOrdersIdComplete = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWorkOrdersIdComplete>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiWorkOrdersIdComplete>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiWorkOrdersIdCompleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    