FROM node:20-alpine
WORKDIR /app
RUN npm install -g pnpm

# コンテナ起動時に pnpm install を実行するためのエントリポイント
COPY entrypoint.dev.sh /entrypoint.dev.sh
COPY entrypoint.storybook.sh /entrypoint.storybook.sh
RUN chmod +x /entrypoint.dev.sh /entrypoint.storybook.sh

EXPOSE 3000
ENTRYPOINT ["/entrypoint.dev.sh"]
