/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Synapse.API | openapi
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateWarehouseRequest,
  GetApiWarehousesParams,
  UpdateWarehouseRequest
} from '../../src/generated/model';

import { apiClient } from '../../src/services/apiClient';




/**
 * @summary 倉庫マスタ一覧を取得する。activeOnly=false で廃止済みも含む。
 */
export const getApiWarehouses = (
    params?: GetApiWarehousesParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/warehouses`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiWarehousesQueryKey = (params?: GetApiWarehousesParams,) => {
    return [
    `/api/warehouses`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiWarehousesQueryOptions = <TData = Awaited<ReturnType<typeof getApiWarehouses>>, TError = unknown>(params?: GetApiWarehousesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWarehouses>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWarehousesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWarehouses>>> = ({ signal }) => getApiWarehouses(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiWarehouses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWarehousesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWarehouses>>>
export type GetApiWarehousesQueryError = unknown


export function useGetApiWarehouses<TData = Awaited<ReturnType<typeof getApiWarehouses>>, TError = unknown>(
 params: undefined |  GetApiWarehousesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWarehouses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWarehouses>>,
          TError,
          Awaited<ReturnType<typeof getApiWarehouses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWarehouses<TData = Awaited<ReturnType<typeof getApiWarehouses>>, TError = unknown>(
 params?: GetApiWarehousesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWarehouses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWarehouses>>,
          TError,
          Awaited<ReturnType<typeof getApiWarehouses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWarehouses<TData = Awaited<ReturnType<typeof getApiWarehouses>>, TError = unknown>(
 params?: GetApiWarehousesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWarehouses>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 倉庫マスタ一覧を取得する。activeOnly=false で廃止済みも含む。
 */

export function useGetApiWarehouses<TData = Awaited<ReturnType<typeof getApiWarehouses>>, TError = unknown>(
 params?: GetApiWarehousesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWarehouses>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWarehousesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary 倉庫を新規作成する。
 */
export const postApiWarehouses = (
    createWarehouseRequest: CreateWarehouseRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/warehouses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createWarehouseRequest, signal
    },
      );
    }
  


export const getPostApiWarehousesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWarehouses>>, TError,{data: CreateWarehouseRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiWarehouses>>, TError,{data: CreateWarehouseRequest}, TContext> => {

const mutationKey = ['postApiWarehouses'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiWarehouses>>, {data: CreateWarehouseRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiWarehouses(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiWarehousesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiWarehouses>>>
    export type PostApiWarehousesMutationBody = CreateWarehouseRequest
    export type PostApiWarehousesMutationError = unknown

    /**
 * @summary 倉庫を新規作成する。
 */
export const usePostApiWarehouses = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWarehouses>>, TError,{data: CreateWarehouseRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiWarehouses>>,
        TError,
        {data: CreateWarehouseRequest},
        TContext
      > => {

      const mutationOptions = getPostApiWarehousesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 倉庫名・倉庫区分を更新する。
 */
export const putApiWarehousesId = (
    id: string,
    updateWarehouseRequest: UpdateWarehouseRequest,
 ) => {
      
      
      return apiClient<void>(
      {url: `/api/warehouses/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateWarehouseRequest
    },
      );
    }
  


export const getPutApiWarehousesIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiWarehousesId>>, TError,{id: string;data: UpdateWarehouseRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiWarehousesId>>, TError,{id: string;data: UpdateWarehouseRequest}, TContext> => {

const mutationKey = ['putApiWarehousesId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiWarehousesId>>, {id: string;data: UpdateWarehouseRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiWarehousesId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiWarehousesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiWarehousesId>>>
    export type PutApiWarehousesIdMutationBody = UpdateWarehouseRequest
    export type PutApiWarehousesIdMutationError = unknown

    /**
 * @summary 倉庫名・倉庫区分を更新する。
 */
export const usePutApiWarehousesId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiWarehousesId>>, TError,{id: string;data: UpdateWarehouseRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiWarehousesId>>,
        TError,
        {id: string;data: UpdateWarehouseRequest},
        TContext
      > => {

      const mutationOptions = getPutApiWarehousesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 倉庫を廃止する（論理削除）。
 */
export const deleteApiWarehousesId = (
    id: string,
 ) => {
      
      
      return apiClient<void>(
      {url: `/api/warehouses/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiWarehousesIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiWarehousesId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiWarehousesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiWarehousesId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiWarehousesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiWarehousesId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiWarehousesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiWarehousesId>>>
    
    export type DeleteApiWarehousesIdMutationError = unknown

    /**
 * @summary 倉庫を廃止する（論理削除）。
 */
export const useDeleteApiWarehousesId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiWarehousesId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiWarehousesId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiWarehousesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    